#!/bin/bash

echo "🔧 Adding Missing Files to Xcode Project"
echo "========================================="
echo ""
echo "The following files need to be added to CalAI.xcodeproj:"
echo ""
echo "1. CalAI/Services/SmartSchedulingService.swift"
echo "2. CalAI/Features/AI/Views/SmartSuggestionView.swift"
echo ""
echo "These files exist but aren't in the Xcode project yet."
echo ""
echo "📝 MANUAL STEPS (Quick & Easy):"
echo "-------------------------------"
echo ""
echo "1. Open Xcode:"
echo "   open CalAI.xcodeproj"
echo ""
echo "2. Add SmartSchedulingService.swift:"
echo "   • In Project Navigator (left sidebar)"
echo "   • Right-click on 'Services' folder"
echo "   • Select 'Add Files to CalAI...'"
echo "   • Navigate to: CalAI/Services/SmartSchedulingService.swift"
echo "   • Make sure 'Copy items if needed' is UNCHECKED"
echo "   • Make sure 'CalAI' target is CHECKED"
echo "   • Click 'Add'"
echo ""
echo "3. Add SmartSuggestionView.swift:"
echo "   • Right-click on 'Features/AI/Views' folder"
echo "   • Select 'Add Files to CalAI...'"
echo "   • Navigate to: CalAI/Features/AI/Views/SmartSuggestionView.swift"
echo "   • Make sure 'Copy items if needed' is UNCHECKED"
echo "   • Make sure 'CalAI' target is CHECKED"
echo "   • Click 'Add'"
echo ""
echo "4. Build (⌘B)"
echo ""
echo "✅ That's it! The errors will be gone."
echo ""
echo "⚠️  Why not automated?"
echo "   Programmatic editing of .xcodeproj files often corrupts them."
echo "   Manual drag-and-drop is safest and takes <1 minute."
echo ""
